{{- if .Values.databases.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.databases.minio.service.type }}
  selector:
    app: minio-{{ .Release.Name }}
  ports:
    - name: minio-data
      port: 9000
      targetPort: 9000
      {{- if (and (eq .Values.databases.minio.service.type "NodePort") .Values.databases.minio.service.dataNodePort) }}
      nodePort: {{ .Values.databases.minio.service.dataNodePort }}
      {{- end }}
    - name: minio-console
      port: 9001
      targetPort: 9001
      {{- if (and (eq .Values.databases.minio.service.type "NodePort") .Values.databases.minio.service.consoleNodePort) }}
      nodePort: {{ .Values.databases.minio.service.consoleNodePort }}
      {{- end }}
{{- end }}
