{{- if .Values.databases.minio.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.databases.minio.ingress.domain }}
    http:
      paths:
      - path: {{ .Values.databases.minio.ingress.prefix }}
        pathType: Prefix
        backend:
          service:
            name: minio-service-{{ .Release.Name }}
            port:
              number: 9001
{{- end }}