{{- if .Values.databases.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  minio-password: {{ .Values.databases.minio.password }}
{{- end }}