{{- if .Values.euler_copilot.rag.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-deploy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rag-{{ .Release.Name }}
spec:
  replicas: {{ .Values.globals.replicaCount }}
  selector:
    matchLabels:
      app: rag-{{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/rag/rag-secret.yaml") . | sha256sum }}
      labels:
        app: rag-{{ .Release.Name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rag
          image: "{{ if ne (.Values.euler_copilot.rag.image.registry | toString ) "" }}{{ .Values.euler_copilot.rag.image.registry }}{{ else }}{{ .Values.globals.imageRegistry }}{{ end }}/{{ .Values.euler_copilot.rag.image.name }}:{{ .Values.euler_copilot.rag.image.tag | toString }}"
          imagePullPolicy: {{ if ne (.Values.euler_copilot.rag.image.imagePullPolicy | toString) "" }}{{ .Values.euler_copilot.rag.image.imagePullPolicy }}{{ else }}{{ .Values.globals.imagePullPolicy }}{{ end }}
          ports:
            - containerPort: 9988
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health_check
              port: 9988
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 90
          env:
            - name: TZ
              value: "Asia/Shanghai"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: rag-config
            - mountPath: /rag-service/data_chain/common
              name: rag-common
          resources:
            {{- toYaml .Values.euler_copilot.rag.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: rag-config
          secret:
            secretName: rag-secret-{{ .Release.Name }}
        - name: rag-common
          secret:
            secretName: rag-secret-{{ .Release.Name }}
{{- end }}

