{{- if .Values.euler_copilot.rag.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rag-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.euler_copilot.rag.service.type }}
  selector:
    app: rag-{{ .Release.Name }}
  ports:
    - port: 9988
      targetPort: 9988
      {{- if (and (eq .Values.euler_copilot.rag.service.type "NodePort") .Values.euler_copilot.rag.service.nodePort) }}
      nodePort: {{ .Values.euler_copilot.rag.service.nodePort }}
      {{- end }}
{{- end }}