{{- if .Values.euler_copilot.rag.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: {{ .Release.Namespace }}
data:
  .env: |-
{{ tpl (.Files.Get "configs/rag/.env") . | indent 4}}
  .env-sql: |-
{{ tpl (.Files.Get "configs/rag/.env-sql") . | indent 4}}
{{- end -}}