FROM hub.oepkgs.net/openeuler/openeuler:24.03-lts-sp2

COPY --from=ghcr.io/astral-sh/uv:0.7.17 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

RUN sed -i 's|repo.openeuler.org|repo.huaweicloud.com/openeuler|g' /etc/yum.repos.d/openEuler.repo && \
    sed -i '/metalink/d' /etc/yum.repos.d/openEuler.repo && \
    sed -i '/metadata_expire/d' /etc/yum.repos.d/openEuler.repo && \
    yum update -y &&\
    yum install -y python3 python3-pip shadow-utils findutils git nodejs npm sudo &&\
    yum install -y mcp-servers-* && \
    yum clean all

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --no-install-project --no-cache-dir