FROM hub.oepkgs.net/openeuler/openeuler:24.03-lts-sp1

COPY --from=ghcr.io/astral-sh/uv:0.6.10 /uv /uvx /bin/
COPY deploy/devstation.repo /etc/yum.repos.d/

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

RUN sed -i 's|repo.openeuler.org|mirrors.nju.edu.cn/openeuler|g' /etc/yum.repos.d/openEuler.repo && \
    sed -i '/metalink/d' /etc/yum.repos.d/openEuler.repo && \
    sed -i '/metadata_expire/d' /etc/yum.repos.d/openEuler.repo && \
    yum update -y &&\
    yum install -y python3 python3-pip shadow-utils findutils git nodejs npm mcp-servers-* &&\
    yum clean all

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --no-dev --no-install-project --no-cache-dir