{{- if .Values.authhub.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.authhub.mysql.service.type }}
  selector:
    app: mysql-{{ .Release.Name }}
  ports:
    - port: 3306
      targetPort: 3306
      {{- if (and (eq .Values.authhub.mysql.service.type "NodePort") .Values.authhub.mysql.service.nodePort) }}
      nodePort: {{ .Values.authhub.mysql.service.nodePort }}
      {{- end }}
{{- end }}