{{- if .Values.authhub.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-password: {{ .Values.authhub.mysql.password }}
  init.sql: |
{{ tpl (.Files.Get "configs/mysql/init.sql") . | indent 4 }}
{{- end }}