{{- if .Values.euler_copilot.deepinsight.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: deepinsight-config
  namespace: {{ .Release.Namespace }}
data:
  .env: |-
{{ tpl (.Files.Get "configs/deepinsight/.env") . | indent 4 }}
  copy-config.yaml: |-
    copy:
      - from: /config/.env
        to: /config-rw/.env
        mode:
          uid: 0
          gid: 0
          mode: "0o650"
        secrets:
          - /db-secrets
          - /system-secrets
{{- end -}}