openapi: 3.0.0
info:
  title: 车牌归属地查询接口
  description: 输入车牌号查询归属地信息
  version: 1.0.0
servers:
  - url: http://shanhe.kim/api/za
paths:
  /chepai.php:
    get:
      summary: 车牌归属地查询
      description: 通过车牌号查询所属省份和城市
      parameters:
        - name: msg
          in: query
          required: true
          schema:
            type: string
          example: 川A
          description: 需要查询的车牌号码
      responses:
        '200':
          description: 成功获取归属地信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          example: 1
          description: 状态码（1表示成功）
        msg:
          type: string
          example: 获取成功!
          description: 操作状态描述
        data:
          type: object
          properties:
            province:
              type: string
              example: 四川
              description: 所属省份
            city:
              type: string
              example: 成都
              description: 所属城市
            abbreviation:
              type: string
              example: 川A
              description: 查询的车牌号