copy:
  - from: /config/aops-config.yml
    to: /config-rw/aops-config.yml
    mode:
      uid: 0
      gid: 0
      mode: "0o650"
    secrets:
      - /db-secrets
      - /authhub-secrets
  - from: /config/conf.d/authhub.yml
    to: /config-rw/conf.d/authhub.yml
    mode:
      uid: 0
      gid: 0
      mode: "0o650"
    secrets:
      - /db-secrets
      - /authhub-secrets
