{{- if .Values.databases.opengauss.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: opengauss-db
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ default "ClusterIP" .Values.databases.opengauss.service.type }}
  selector:
    app: opengauss
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ default nil .Values.databases.opengauss.service.nodePort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengauss-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: opengauss
spec:
  replicas: {{ default 1 .Values.globals.replicaCount }}
  selector:
    matchLabels:
      app: opengauss
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opengauss/opengauss-config.yaml") . | sha256sum }}
      labels:
        app: opengauss
    spec:
      automountServiceAccountToken: false
      containers:
        - name: opengauss
          image: image: {{ .Values.databases.opengauss.image | default (printf "%s/neocopilot/opengauss:latest-%s" (.Values.globals.imageRegistry | default "hub.oepkgs.net") (ternary "arm" "x86" (eq (.Values.globals.arch | default "x86") "arm"))) }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.globals.imagePullPolicy }}
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - gs_guc reload -D /var/lib/opengauss/data -c "behavior_compat_options='accept_empty_str'"
                - pg_isready
                - -d postgres -U postgres
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 90
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: GS_DB
              value: "postgres"
            - name: GS_USERNAME
              value: "postgres"
            - name: GS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: euler-copilot-database
                  key: gauss-password
          volumeMounts:
            - mountPath: /var/lib/opengauss/data
              name: opengauss-data
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: opengauss-init
              subPath: init.sql
          resources:
            requests:
              cpu: 0.25
              memory: 512Mi
            limits:
                {{ toYaml .Values.databases.opengauss.resourceLimits | indent 4 | trim }}
      volumes:
        - name: opengauss-data
          persistentVolumeClaim:
            claimName: opengauss-storage
        - name: opengauss-init
          configMap:
            name: opengauss-config
{{- end -}}

