{{- if .Values.euler_copilot.framework.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: framework-config
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |-
{{ tpl (.Files.Get "configs/framework/config.toml") . | indent 4 }}
  copy-config.yaml: |-
{{ tpl (.Files.Get "configs/framework/copy-config.yaml") . | indent 4 }}
{{- end -}}