[deploy]
mode = 'local'
cookie = 'domain'

[login]
provider = 'authhub'

[login.settings]
app_id = '1234567890'
app_secret = '1234567890'

[service]
rag_service = ''

[embedding]
type = 'openai'
endpoint = ''
api_key = ''
model = 'bge-m3'

[fastapi]
domain = 'http://127.0.0.1:8001'
jwt_key = '1234567890'

[security]
half_key1 = ''
half_key2 = ''
half_key3 = ''

[mongodb]
host = '127.0.0.1'
port = 27017
user = '1234567890'
password = '1234567890'
database = '1234567890'

[minio]
endpoint = '127.0.0.1:9001'
access_key = '1234567890'
secret_key = '1234567890'
secure = false

[llm]
llm_key = '1234567890'
llm_url = 'http://127.0.0.1:8001'
llm_model = 'gpt-3.5-turbo'
llm_max_tokens = 1000
llm_temperature = 0.5

[scheduler]
scheduler_backend = 'openai'
scheduler_model = 'gpt-3.5-turbo'
scheduler_url = 'http://127.0.0.1:8001'
scheduler_api_key = '1234567890'
scheduler_max_tokens = 1000
scheduler_temperature = 0.5

[detect]
detect_type = 'openai'
detect_url = 'http://127.0.0.1:8001'
detect_api_key = '1234567890'
detect_model = 'gpt-3.5-turbo'
detect_max_tokens = 1000
detect_temperature = 0.5
