[deploy]
mode = 'local'
cookie = 'domain'
data_dir = '/app/data'

[login]
provider = 'authhub'
[login.settings]
host = ''
host_inner = ''
login_api = 'https://www.eulercopilot.local/api/auth/login'
app_id = ''
app_secret = ''

[fastapi]
domain = 'www.eulercopilot.local'
csrf = false

[security]
half_key1 = ''
half_key2 = ''
half_key3 = ''
jwt_key = ''

[embedding]
type = 'openai'
endpoint = 'https://api.openai.com/v1'
api_key = ''
model = 'bge-m3'

[rag]
rag_service = ''

[mongodb]
host = ''
port = 27017
user = 'euler_copilot'
password = ''
database = 'euler_copilot'

[minio]
endpoint = ''
access_key = 'minioadmin'
secret_key = ''
secure = false

[llm]
endpoint = 'https://api.openai.com/v1'
key = ''
model = 'gpt-4o-mini'
max_tokens = 8192
temperature = 0.7

[function_call]
backend = 'ollama'
endpoint = 'http://localhost:11434'
model = 'llama3.1:8b'
api_key = ''
max_tokens = 8192
temperature = 0.7

[check]
enable = false
words_list = ""
