{{- if .Values.euler_copilot.rag_web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rag-web-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.euler_copilot.rag_web.service.type }}
  selector:
    app: rag-web-{{ .Release.Name }}
  ports:
    - port: 9888
      targetPort: 9888
      {{- if (and (eq .Values.euler_copilot.rag_web.service.type "NodePort") .Values.euler_copilot.rag_web.service.nodePort) }}
      nodePort: {{ .Values.euler_copilot.rag_web.service.nodePort }}
      {{- end }}
{{- end }}

