copy:
  - from: /config/.env
    to: /config-rw/.env
    mode:
      uid: 1001
      gid: 1001
      mode: "0o650"
    secrets:
      - /db-secrets
      - /system-secrets
  - from: /config/.env-sql
    to: /config-rw/.env-sql
    mode:
      uid: 1001
      gid: 1001
      mode: "0o650"
    secrets:
      - /db-secrets
      - /system-secrets
