{{- if .Values.databases.mongo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongo-password: {{ .Values.databases.mongo.password }}
  healthcheck.sh: |
{{ tpl (.Files.Get "configs/mongo/healthcheck.sh") . | indent 4 }}
{{- end }}